// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEv_DGaceJFRUl72XZ0nEff2DYlyog0yg',
    appId: '1:145125421775:web:af34e323b93dcdb733bdba',
    messagingSenderId: '145125421775',
    projectId: 'foodly-restaurant-2025',
    authDomain: 'foodly-restaurant-2025.firebaseapp.com',
    storageBucket: 'foodly-restaurant-2025.firebasestorage.app',
    measurementId: 'G-36R0SB30NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9w9YVJsaq0D0V_qkWOFmug-bLRgHYyd8',
    appId: '1:145125421775:android:fee99686ddf46ab733bdba',
    messagingSenderId: '145125421775',
    projectId: 'foodly-restaurant-2025',
    storageBucket: 'foodly-restaurant-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIX6SzjIbXmnqeee4Y_GaW0NKZE_rR50g',
    appId: '1:145125421775:ios:dd7ac7c7569539d333bdba',
    messagingSenderId: '145125421775',
    projectId: 'foodly-restaurant-2025',
    storageBucket: 'foodly-restaurant-2025.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFoodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIX6SzjIbXmnqeee4Y_GaW0NKZE_rR50g',
    appId: '1:145125421775:ios:dd7ac7c7569539d333bdba',
    messagingSenderId: '145125421775',
    projectId: 'foodly-restaurant-2025',
    storageBucket: 'foodly-restaurant-2025.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFoodly',
  );
}
